name = "thevoid"
main = "src/index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "VOID_ROOM", class_name = "VoidRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["VoidRoom"]

[assets]
directory = "./public"
